//
//  ItemRepository.swift
//  Fizzle
//
//  Created by Kyle Peterson on 11/22/24.
//

import Foundation

// Item Repository Singleton
class ItemRepository {
    static let shared = ItemRepository()
    
    private(set) var items: [Item] = []
    
    private init() {
        let items = [
            Item(
                name: "A.P. Arrow",
                type: .weapon,
                weight: 0.2,
                cost: 45,
                toHitBonus: 2,
                damage: Damage(numberOfDice: 1, diceSides: 8, bonus: 4),
                armorClass: nil,
                spellAndPower: nil,
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                weaponHand: .secondary,
                isTwoHanded: false,
                range: .shoot,
                fightingModes: [.thrust],
                powers: []
            ),
            Item(
                name: "Acid Bomb",
                type: .potion,
                weight: 0.4,
                cost: 1200,
                toHitBonus: 0,
                damage: Damage(numberOfDice: 0, diceSides: 0, bonus: 0),
                armorClass: nil,
                spellAndPower: ["Acid Bomb": 4],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                weaponHand: .secondary,
                isTwoHanded: false,
                range: .thrown,
                fightingModes: [.thrown],
                powers: []
            ),
            Item(
                name: "Amulet of Air",
                type: .armor,
                weight: 1.0,
                cost: 4500,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: ["Air Pocket": 5],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                weaponHand: nil,
                isTwoHanded: nil,
                range: .short,
                fightingModes: [],
                powers: []
            ),
            Item(
                name: "Amulet of Ice",
                type: .armor,
                weight: 1.0,
                cost: 10000,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: ["Ice Shield": 4],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                weaponHand: nil,
                isTwoHanded: nil,
                range: .short,
                fightingModes: [],
                powers: []
            ),
            Item(
                name: "Amulet of Life",
                type: .armor,
                weight: 1.0,
                cost: 25000,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: ["Resurrection": 6],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                isTwoHanded: nil,
                range: .short,
                fightingModes: [],
                powers: []
            ),
            Item(
                name: "Amulet of Night",
                type: .armor,
                weight: 1.0,
                cost: 2500,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: ["Blinding Flash": 4],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                isTwoHanded: nil,
                range: .short,
                fightingModes: [],
                powers: []
            ),
            Item(
                name: "Amulet of Winds",
                type: .armor,
                weight: 1.0,
                cost: 10000,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: ["Whirlwind": 4],
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                isTwoHanded: nil,
                range: .short,
                fightingModes: [],
                powers: []
            ),
            Item(
                name: "Ancient Dust",
                type: .miscellaneous,
                weight: 0.5,
                cost: 200,
                toHitBonus: nil,
                damage: nil,
                armorClass: nil,
                spellAndPower: nil,
                allowedProfessions: Profession.allCases,
                allowedRaces: Race.allCases,
                allowedSexes: [.male, .female],
                weaponHand: .secondary,
                isTwoHanded: false,
                range: .thrown,
                fightingModes: [],
                powers: []
            ),
//            Item(
//                name: "Angel's Tongue",
//                type: .miscellaneous,
//                weight: 2.0,
//                cost: 50000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Help Food": 3],
//                allowedProfessions: [.bard],
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                weaponHand: nil,
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Arnie",
//                type: .armor,
//                weight: 1.5,
//                cost: 20000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Death": 5],
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Death",
//                type: .armor,
//                weight: 0.5,
//                cost: 25000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Death": 5],
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Life",
//                type: .armor,
//                weight: 1.5,
//                cost: 50000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Resurrection": 6],
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Might",
//                type: .armor,
//                weight: 1.5,
//                cost: 20000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Phyre",
//                type: .armor,
//                weight: 1.5,
//                cost: 100000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Fireball": 3],
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Purity",
//                type: .armor,
//                weight: 1.5,
//                cost: 1000000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Sanctity",
//                type: .armor,
//                weight: 1.5,
//                cost: 500000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Wonder",
//                type: .armor,
//                weight: 1.5,
//                cost: 20000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Ankh of Youth",
//                type: .armor,
//                weight: 1.5,
//                cost: 25000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Anointed Cloak",
//                type: .armor,
//                weight: 6.0,
//                cost: 40000,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: ["Armor Shield": 2],
//                allowedProfessions: [.priest, .ranger, .valkyrie, .bishop, .lord, .monk],
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                name: "Anointed Flail",
//                type: .weapon,
//                weight: 15.0,
//                cost: 140,
//                toHitBonus: 1,
//                damage: Damage(numberOfDice: 1, diceSides: 6, bonus: 1),
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: [.priest, .ranger, .valkyrie, .bishop, .lord, .ninja],
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: true,
//                range: .short,
//                fightingModes: [.swing],
//                powers: []
//            ),
//            Item(
//                name: "Apple",
//                type: .miscellaneous,
//                weight: 0.2,
//                cost: 150,
//                toHitBonus: nil,
//                damage: nil,
//                armorClass: nil,
//                spellAndPower: nil,
//                allowedProfessions: Profession.allCases,
//                allowedRaces: Race.allCases,
//                allowedSexes: [.male, .female],
//                isTwoHanded: nil,
//                range: nil,
//                fightingModes: [],
//                powers: []
//            ),
//            Item(
//                    name: "Armet",
//                    type: .armor,
//                    weight: 7.5,
//                    cost: 7000,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: 10,
//                    spellAndPower: nil,
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Armor Shield",
//                    type: .scroll,
//                    weight: 0.3,
//                    cost: 200,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: nil,
//                    spellAndPower: ["Armor Shield": 2],
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Armorplate",
//                    type: .scroll,
//                    weight: 0.3,
//                    cost: 200,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: nil,
//                    spellAndPower: ["Armorplate": 3],
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Awl Pike",
//                    type: .weapon,
//                    weight: 12.0,
//                    cost: 50,
//                    toHitBonus: 2,
//                    damage: Damage(numberOfDice: 1, diceSides: 6, bonus: 1),
//                    armorClass: nil,
//                    spellAndPower: nil,
//                    allowedProfessions: [.priest, .ranger, .valkyrie, .bishop, .lord, .monk],
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: true,
//                    range: .extended,
//                    fightingModes: [.thrust],
//                    powers: []
//                ),
//                Item(
//                    name: "Axe of Woe",
//                    type: .weapon,
//                    weight: 18.0,
//                    cost: 6500,
//                    toHitBonus: -8,
//                    damage: Damage(numberOfDice: 2, diceSides: 6, bonus: 2),
//                    armorClass: nil,
//                    spellAndPower: nil,
//                    allowedProfessions: [.priest, .ranger, .valkyrie, .bishop, .lord],
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: true,
//                    range: .short,
//                    fightingModes: [.swing],
//                    powers: []
//                ),
//                Item(
//                    name: "B.D. Key",
//                    type: .miscellaneous,
//                    weight: 0.0,
//                    cost: 0,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: nil,
//                    spellAndPower: nil,
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Bag of Sand",
//                    type: .miscellaneous,
//                    weight: 20.0,
//                    cost: 0,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: nil,
//                    spellAndPower: nil,
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Barbed Arrow",
//                    type: .weapon,
//                    weight: 0.3,
//                    cost: 25,
//                    toHitBonus: 0,
//                    damage: Damage(numberOfDice: 1, diceSides: 8, bonus: 4),
//                    armorClass: nil,
//                    spellAndPower: nil,
//                    allowedProfessions: [.ranger, .valkyrie],
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: .short,
//                    fightingModes: [.shoot],
//                    powers: []
//                ),
//                Item(
//                    name: "Bascinet",
//                    type: .armor,
//                    weight: 6.5,
//                    cost: 8000,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: 9,
//                    spellAndPower: nil,
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                ),
//                Item(
//                    name: "Bascinet & Camail",
//                    type: .armor,
//                    weight: 8.0,
//                    cost: 15000,
//                    toHitBonus: nil,
//                    damage: nil,
//                    armorClass: 10,
//                    spellAndPower: nil,
//                    allowedProfessions: Profession.allCases,
//                    allowedRaces: Race.allCases,
//                    allowedSexes: [.male, .female],
//                    isTwoHanded: nil,
//                    range: nil,
//                    fightingModes: [],
//                    powers: []
//                )
        ]
    }
}
